### ISSUE TITLE
Use @reboot instead of minute/hour for on-reboot display-off.sh?

### ISSUE THREAD

**Issue by SnorreSelmer** [futurice/chilipie-kiosk#102]
When cron reboots the Pi, is there a reason why the crontab has a hardcoded delay to shut off displays? 
If you replace the time with @reboot, then the command will run as soon as the boot process will allow it.

**Comment by jareware** [comment]
The reason why it's timed is we don't want to turn off the display after every boot (e.g. a user-initiated one, or accidental one while the display should be on). We only want to keep the display off when the Pi reboots while the display was already off.

That said, as the `crontab.example` name implies, this is just an example config, and folks can change it if they please!
