### ISSUE TITLE
Include ntp in base image?

### ISSUE THREAD

**Issue by SnorreSelmer** [futurice/chilipie-kiosk#104]
The rPi doesn't have a RTC backup battery, and the clock slips a little bit every day. HTTPS has a security feature that if the requester's system-time is off by too much, HTTPS websites won't load.
With ntp pre-installed, system-time would always be very accurate.

**Comment by jareware** [comment]
Honestly I was under the impression Raspbian already shipped with one... :thinking: but I'll take your word for it (can't check right now).

PR would be welcome!

**Comment by SnorreSelmer** [comment]
sudo apt installerer ntp installs two packages, so apparently not. :-)

**Comment by allcoolusernamesaregone** [comment]
the ntp client was replaced with systemd-timesyncd in raapbian strech i think.
there should be no need for ntp If one just need the correct time after a reboot...?

**Comment by jareware** [comment]
I can't say I've noticed the clock slipping on any of mine, so I'd be inclined to assume what @allcoolusernamesaregone said.

**Comment by SnorreSelmer** [comment]
Ah ok. Must be some networking issue regarding the NTP protocol on our end
then. *sigh* _Another_ thing I need to bug the networking/firewall people
about. Thanks for the help though!

**Comment by jareware** [comment]
np!
