### ISSUE TITLE
On-screen keyboard

### ISSUE THREAD

**Issue by Dario-Ciceri** [futurice/chilipie-kiosk#111]
Hi, I can't see any on-screen keyboard when I touch a text field, how to install?

**Comment by allcoolusernamesaregone** [comment]
did you try https://github.com/futurice/chilipie-kiosk/issues/63#issuecomment-566209247 ?

**Comment by Dario-Ciceri** [comment]
> did you try [#63 (comment)](https://github.com/futurice/chilipie-kiosk/issues/63#issuecomment-566209247) ?

yes and didn't work the first time, then I have installed an extensione to ignore xframe and it works!

**Comment by allcoolusernamesaregone** [comment]
Which extension to ignore xframe? Just curious..

**Comment by Dario-Ciceri** [comment]
> Which extension to ignore xframe? Just curious..
just search on chrome webstore for ignore x frame, the first one
