### ISSUE TITLE
How to open Browser with 2 default Websites and define Whitelist?

### ISSUE THREAD

**Issue by blueicehaller** [futurice/chilipie-kiosk#112]
Hi,
on an Raspberry Pi 4 I connected the following Display with Touchscreen:
Iiyama ProLite T2735MSC

Previously I used Porteus Kiosk on x86 which is using Mozilla Firefox and is able to 
1) open minimal Browser in F11 Fullscreen and show 2 Tabs (default Webites) on startup
2) Maintain a Website whitelist
3) Hide address field

Is it possible to do the same with Chromium or Mozilla Firefox on Chilipie?

I already defined 2 default Websites.

Thank you in advance.

**Comment by jareware** [comment]
Sorry for taking a long time to get back to this.

There's no built-in support for showing 2 sites at the same time, unfortunately.

As to white-listing, you can definitely do something on the system level (or maybe using some Chrome extension?). That said, the kiosk isn't really hardened for adversarial users - if someone has physical access, they can probably break out of the browser.

**Comment by blueicehaller** [comment]
That's OK. I updated my requirements with my current situation.

**Comment by jareware** [comment]
Thanks for detailing your setup, might be useful for someone looking to do the same!
