### ISSUE TITLE
Portrait mode problem

### ISSUE THREAD

**Issue by klaaskox** [futurice/chilipie-kiosk#117]
I am using `display_rotate=3` in `/boot/config.txt` to rotate the screen. Now the orientation of the screen is correct, however, the dimensions of the viewport/monitor seem too be wrong, see attached image.

![rotation_problem](https://user-images.githubusercontent.com/5795166/83614212-306e7480-a585-11ea-9df8-eca3fa84c1e5.jpg)

What can I do to make the browser fit the monitor?

**Comment by klaaskox** [comment]
I think I found the solution (Raspberry Pi 4). 

disabled vc4-fkms-v3d in `/boot/config.txt`:
`#dtoverlay=vc4-fkms-v3d`

added rotation to `/boot/config.txt`:
`display_hdmi_rotate=3`

**Comment by klaaskox** [comment]
I think I found the solution (Raspberry Pi 4). 

disabled vc4-fkms-v3d in `/boot/config.txt`:
`#dtoverlay=vc4-fkms-v3d`

added rotation to `/boot/config.txt`:
`display_hdmi_rotate=3`

**Comment by wujood** [comment]
You do not need to disable dtoverlay since this might reduce performance (especially for videos). Please look at issue https://github.com/futurice/chilipie-kiosk/issues/92
