### ISSUE TITLE
display_server_not_supported

### ISSUE THREAD

**Issue by 60999** [futurice/chilipie-kiosk#120]
when use anydesk ,client will shwo "display_server_not_supported" and disconnect,why？
————how to install————————

sudo apt install ./anydesk_5.5.5-1_armhf.deb -y
sudo anydesk --service
anydesk --get-alias
sudo echo password |sudo  anydesk --set-password

------------------------
but It running in 2020-05-27-raspios-buster-armhf.zip goodly.

**Comment by jareware** [comment]
Not sure if actionable. 🤔
