### ISSUE TITLE
Is there a way to auto-refresh the webpage?

### ISSUE THREAD

**Issue by jmetelski** [futurice/chilipie-kiosk#124]
Hello. I wanted to know if is there a way to auto refresh the current website, for example every X minutes? Thanks!

**Comment by Quafi** [comment]
Sure thing! Just add a crontab like this: `* /15 * * * * xdotool key ctrl+R`

This will reloaded the current tab every 15 minutes. You can adjust that as you whish.

**Comment by jmetelski** [comment]
> Sure thing! Just add a crontab like this: `* /15 * * * * xdotool key ctrl+R`
> 
> You can access the crontabs using "crontab - e". They'll need a reboot to be applied.
> 
> This will reloaded the current tab every 15 minutes. You can adjust that as you wish.

Thanks!
