### ISSUE TITLE
how use image-setup.sh?

### ISSUE THREAD

**Issue by jonahzheng** [futurice/chilipie-kiosk#127]
thank you.
I want creat a image

> lvzx% cd docs                 
cd: no such file or directory: docs
lvzx% sudo sh ./image-setup.sh
Password:
-e 
🛑  Enter version (e.g. "1.2.3") being built:
3.0.2
-e 
✨  Updating version file
-e 
✨  Generating first-boot.html
npm WARN saveError ENOENT: no such file or directory, open '/Users/lvzx/java/chilipie-kiosk/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/lvzx/java/chilipie-kiosk/package.json'
npm WARN chilipie-kiosk No description
npm WARN chilipie-kiosk No repository field.
npm WARN chilipie-kiosk No README data
npm WARN chilipie-kiosk No license field.
+markdown-styles@3.1.10
+html-inline@1.2.0
updated 2 packages and audited 192 packages in 8.348s
found 33 vulnerabilities (14 low, 8 moderate, 11 high)
  run `npm audit fix` to fix them, or `npm audit` for details
./image-setup.sh: line 39: ./node_modules/.bin/generate-md: No such file or directory
./image-setup.sh: line 40: ./node_modules/.bin/html-inline: No such file or directory
-e 
🛑  Mount the SD card (press enter when ready)

**Comment by jareware** [comment]
Good luck!
