### ISSUE TITLE
Not display mouse cursor

### ISSUE THREAD

**Issue by FXUDarkNova** [futurice/chilipie-kiosk#128]
I am using a touch screen and wish to not have the cursor appear when screen is touched I have tried changing  unclutter -idle 0 -root & in .xsession which didn't work is there another way to achieve what I want?

**Comment by jareware** [comment]
Hmm, you might be able to change X settings to use a different cursor, and use a fully transparent one.

Haven't tried that, though.

**Comment by FXUDarkNova** [comment]
I shall give that ago thank you
