### ISSUE TITLE
Is this compatible with Raspberry Pi 4?

### ISSUE THREAD

**Issue by juanjosezg** [futurice/chilipie-kiosk#136]
Is this version or any fork compatible with the current version of raspberry pi 4?

**Comment by ThisIsTenou** [comment]
I can't say anything about forks, but there are release candidates for the Pi4 available: https://github.com/futurice/chilipie-kiosk/releases

**Comment by jareware** [comment]
This is indeed true, and we'll try to get a non-RC release out soon, too.

Thanks for providing support @ThisIsTenou!
