### ISSUE TITLE
Project overhaul

### ISSUE THREAD

**Issue by markovchainz** [futurice/chilipie-kiosk#137]
As discussed in #135, I am forking this project with the intention of performing a major overhaul.

If anyone is willing to help out, give me a shout.

I don't have a whole load of time available so I can't make any promises on a clear timeline.

**Comment by heatxsink** [comment]
I'm down to help.

**Comment by jareware** [comment]
Please see my response in https://github.com/futurice/chilipie-kiosk/issues/135#issuecomment-784988512 for the current status, and how you can help!
