### ISSUE TITLE
See about shrinking the image further

### ISSUE THREAD

**Issue by jareware** [futurice/chilipie-kiosk#14]
http://www.aoakley.com/articles/2015-10-09-resizing-sd-images.php

**Comment by adriengibrat** [comment]
chilipie-kiosk-v1.2.1 image is 8.1G, so I had to resize second partition to dd on a 8G sd card

**Comment by jareware** [comment]
Oh, interesting! Can you elaborate on the specific `dd` invocation you used?

**Comment by jareware** [comment]
The [2.0.0 release](https://github.com/futurice/chilipie-kiosk/releases/tag/v2.0.0) significantly shrinks the image (by over 50%).
