### ISSUE TITLE
Exit full screen after crontab refresh

### ISSUE THREAD

**Issue by federicotravaini** [futurice/chilipie-kiosk#145]
Hi,
I've been dealing with this issue for the past days and I can't solve it in a stable way.
I set up a crontab job to refresh the page every x minutes using xdotool key F5
When the refresh happens, Chromium exits full screen but I have no idea why.

I fixed it temporaly adding a `&& sleep 1 && xdotool key F11` but I don't like this solution.

Ever experienced this issue?

**Comment by jareware** [comment]
Haven't heard of this before, and maybe you already got it sorted (or gave up) already. 😅

**Comment by federicotravaini** [comment]
I don't know why but it happens sometimes and disappears randomly withouth me doing anything.
