### ISSUE TITLE
Remote desktop not working

### ISSUE THREAD

**Issue by federicotravaini** [futurice/chilipie-kiosk#148]
Hi, I tried to install `sudo apt-get install xrdp` but when I try to connect with Windows 10 Remote Desktop the screen goes black. MIght be a good idea to include `xrdp`?

**Comment by jareware** [comment]
There's a separate issue for (more easily) enabling remote access, including VNC etc. I think this goes into the same category, and should be solved at the same time.

There's already SSH, if you enable it, though, and you can install `xrdp` yourself if you need it!
