### ISSUE TITLE
WLAN keeps losing gateway

### ISSUE THREAD

**Issue by SnorreSelmer** [futurice/chilipie-kiosk#173]
I'm not sure if this is a ChiliPie issue or not, but here goes.

We use ChiliPie at work to monitor Grafana and Kibana dashboards. After a recent upgrade of Kibana, ChiliPie 2 stopped loading Kibana, so we upgraded one of our rPis to ChiliPi 3.0.0 to test.

ChiliPie 3.0.0 works great, except that it keeps forgetting the network gateway for our IoT WLAN. We can maually set the gateway (`route add default gw [IP-address]`), but within a few minutes, the information is lost again.

I've tried to reproduce the same conditions at home (client isolation WLAN without SSID broadcast) without success.

**Comment by SnorreSelmer** [comment]
Well, this is embarrassing...
So, I ran an `apt upgrade` on the system today just in case. One of the packages that updated was `dhcpcd`, and now it seems it might work without kludgy workarounds (for the first time ever)!
I'll test this for a couple of days and then close the issue if it's actually fixed.

**Comment by SnorreSelmer** [comment]
I've managed to find that this happens because `dhcpcd` insists on sending DUID to our Windows Server 2012 DHCP server (which is apparently a buggy mess that won't return a lease unless you send a MAC-address), and it has nothing to do with ChiliPie. (The problem exists in RaspberryOS 11 as well...)
`dhclient` works fine, `dhcpcd` doesn't, and I'm trying to find a way to make `dhcpcd` do what it's supposed to.

@jareware , you're welcome to close this issue if you want, I'm leaving it open for for purposes of reporting any fix I might find.

**Comment by jareware** [comment]
That sounds odd. 😳  Don't have ideas off the top of my head, sorry.

Feel free to report back if you find a fix. 🙇

**Comment by SnorreSelmer** [comment]
I managed to fix it yesterday. There are some places where you can add exit-hooks to `dhcpcd` and `dhclient`, but none of them seemed to work, so I ended up adding a file (`99-gateway`) to the `/lib/dhcpcd/dhcpcd-hooks/` folder with `/usr/sbin/route add default gw [gateway IP]` in it. That way, every time DHCP is invoked, the gateway is set anew. Once we replace the offending DHCP server, I should be able to undo all this and let `dhcpcd` do it's thing.
