### ISSUE TITLE
how to rotate display in .xsession SOLVED

### ISSUE THREAD

**Issue by anthonymobile** [futurice/chilipie-kiosk#174]
inserting this into `/home/pi/.xsession` does nothing, though running it on the command line works fine:

```
xrandr -display :0.0 --output HDMI-1 --mode 1920x1080 --rate 50 --rotate left
```
it also doesn't effect the display if i run it in `.bashrc` or as a `systemctl` service or `rc.local` or any of the normal methods. what am i doing wrong?

**Comment by anthonymobile** [comment]
solution was to move the command up to the top of the `.xsession` file, just after `export DISPLAY=:0.0` and simplified to
`xrandr --output HDMI-1 --rotate left`

**Comment by shanerehm1234** [comment]
Thank you so much for posting this! I've been trying to figure this out for 2 days!
