### ISSUE TITLE
Ansible automation

### ISSUE THREAD

**Issue by chriso0710** [futurice/chilipie-kiosk#19]
Great instructions!
Maybe you would like to take a look at https://github.com/chriso0710/pikiosk, which fully automates a Chromium kiosk based on Raspbian Jessie with Ansible.

Christian

**Comment by jareware** [comment]
Interesting, will definitely take a look! I've been thinking of "rebasing" on Raspbian too.

**Comment by jareware** [comment]
The [2.0.0 release](https://github.com/futurice/chilipie-kiosk/releases/tag/v2.0.0) significantly automates the build process.
