### ISSUE TITLE
Setting Startup URL via --app does not work

### ISSUE THREAD

**Issue by MaXFalstein** [futurice/chilipie-kiosk#25]
Chrome is able to accept `--app "http://github.com"` but it does not work with Chilipie Kiosk.

**Comment by jareware** [comment]
Good point, and this is definitely on the radar!

In those cases the biggest hurdle is usually this: most people's dashboards aren't going to be publicly available on the Internet, so you'd still need to authenticate, with a login form or something. Being able to specify that via command line args/SSH is more complicated.

**Comment by loranger** [comment]
Yes, you're right. If the webpage uses a http basic auth, it's quite simple to define the user and password in the url, but for a advanced auth process, you have to use a mouse and keyboard…

… Maybe for all the other url, that would be useful ?

**Comment by jareware** [comment]
Created #31 to track this.
