### ISSUE TITLE
Version 1.2.1 does not seem to fit on a 8gb memory card

### ISSUE THREAD

**Issue by olpeh** [futurice/chilipie-kiosk#29]
```
dd: error writing '/dev/mmcblk0p1': No space left on device
7580+0 records in
7579+0 records out
7947157504 bytes (7,9 GB, 7,4 GiB) copied, 585,139 s, 13,6 MB/s
```

![screenshot_2018-08-01_13-30-16](https://user-images.githubusercontent.com/6113341/43516874-864e2f24-958f-11e8-8efd-e9974a9945b6.png)

**Comment by olpeh** [comment]
If this is the case, the instructions should be updated and the link to Verkkokauppa should be updated as well.

**Comment by jareware** [comment]
I'm wondering if #27 might have something to do with this, i.e. being platform dependent for `dd`..? I could have sworn I've also flashed 8 GB cards with that. 🤔 

I'll actually change the README to suggest using https://etcher.io/ for the next release anyway, because it's just so nice to use.

**Comment by olpeh** [comment]
Etcher is really nice. And the screenshot is from etcher. 
I'll just go grab a bigger card for now and will close #27 and reject #28

**Comment by jareware** [comment]
OK.

Thanks for reporting this, I'll address this with the next build.

Sorry for the trouble.

**Comment by jareware** [comment]
This should not be an issue since the 2.x.
