### ISSUE TITLE
Ensuring Chromium can output sound over HDMI

### ISSUE THREAD

**Issue by jareware** [futurice/chilipie-kiosk#3]
It already might, I honestly just haven't checked.

**Comment by GeorgeWilkins** [comment]
In case you've haven't tried this yet; audio over HDMI works fine out of the box.

**Comment by jareware** [comment]
I actually hadn't, thanks a lot for confirming this!

**Comment by jaruba** [comment]
@jareware I actually tried this today, and sound over HDMI does not work for me (tested on RPI 3 B and RPI 4 B)

**Comment by alteoxCOM** [comment]
Did anyone find a solution to playback sound via HDMI?
