### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by Oyvindespnes** [futurice/chilipie-kiosk#43]
Is there a way to create a subtle TABS- button? To either toggle between tabs or simply choose one?
Or show only the TABS bar?

**Comment by jareware** [comment]
Hey, sorry for taking some time to get back to this, I've been away from the keyboard for a while.

I would say your best bets are either:

1. Finding a Chrome extension that does it for you (installing extensions is detailed in the [first boot doc](https://github.com/futurice/chilipie-kiosk/blob/master/docs/first-boot.md#customizing-chromium))
1. Just showing the tabs bar

Good luck!
