### ISSUE TITLE
prompt on startup

### ISSUE THREAD

**Issue by loranger** [futurice/chilipie-kiosk#44]
Hello,

I recently did a system upgrade on my pis and unfortunately on my chilipie-kiosk.
Everything work flawlessly, but now, I have to type in my login and password on every reboot in order to start x server, then the boot process starts as usual.

Is there anything to edit in order to start x automatically ?

**Comment by nick-laird** [comment]
Run `sudo raspi-config` or switch to TTY2 with CTRL+ALT+F2 and pick option 3 Boot Options. Then select option B2 console auto login. It will fix the issue.

**Comment by loranger** [comment]
Thank you so much !
