### ISSUE TITLE
Guideline for Contribution

### ISSUE THREAD

**Issue by nyinyinyanlin** [futurice/chilipie-kiosk#45]
I'm currently developing a digital signage solution and in much love with this cool project. I would love to contribute to this project and bring a few more features. I didn't use the raspbian image provide though, I only used configurations provided by this project.

I want to stick to guidelines and rules if there is any, and make pull requests. And any documentation on packages and settings used in "raspbian image" would be appreciated.

Thank you so much.

**Comment by jareware** [comment]
Hey, sorry for taking some time to get back to this, I've been away from the keyboard for a while.

As to which packages are used, check out #42 for a complete answer!

As to contributing features back, there's currently no specific guidelines, and I suppose it might be a good idea to add some! In the mean time, the best way to suggest new features is to [open an issue with the "enhancement" tag](https://github.com/futurice/chilipie-kiosk/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement). There's already a few in there, waiting for someone to get around to implementing them. Keep in mind, though, that the core values of the project are stability, and ease of use, so features that branch too far from those may have to stay in a fork.

Hope this helps!
