### ISSUE TITLE
x86 support

### ISSUE THREAD

**Issue by brunoshine** [futurice/chilipie-kiosk#50]
Hi,
first of all great work. I've been using to run digital signage with great success. 
Have you tested in a x86 chipset, like an intel i7, for instance, without changes?

Thanks
Bruno

**Comment by jareware** [comment]
Thanks!

Unfortunately, there's currently no support for other architectures.

You're not the first one to ask, though, and as detailed in #42, it's probably not too hard to set up.

If you make progress, please report back, and we'll see about adding an official release!
