### ISSUE TITLE
Watchdog

### ISSUE THREAD

**Issue by matristain** [futurice/chilipie-kiosk#51]
For this Raspian / kernel version to activate watchdog
Simply edit /etc/systemd/system.conf 
to include 
"RuntimeWatchdogSec=14"?

**Comment by jareware** [comment]
That's a good point! According to [this answer](https://raspberrypi.stackexchange.com/questions/85193/rpi3-is-the-hardware-watchdog-enabled-by-default) it's enabled by default, but I'll need to check.

**Comment by jareware** [comment]
I can also see the watchdog being initialized in `dmesg`.

Do you have a way of testing whether it actually works? I'm not sure I do... 🤔

**Comment by jareware** [comment]
Based on my best understanding, the watchdog IS active, (at least) as of release `v2.1.0`.

Closing this for now, please reopen if you have more info.
