### ISSUE TITLE
Any thoughts of making a container version or script to create image?

### ISSUE THREAD

**Issue by MacRonin** [futurice/chilipie-kiosk#53]
I was looking to potentially use this in conjunction with some other tools. but each assume that they are the boot image. I figure there are two ways to have them work together.
- Have Chilipie in a Docker container and run alongside the or
- have some type of script (or ansible.com type playlist) that creates the environment. This could then be used to create a full SDcard image or Docker type container

I haven't finalized any decision but an example of what I would like to work with is something like Belena ( https://www.balena.io/what-is-balena/ ) or similar ( with a preference for open-source)

Are there any plans in this direction?
*Feature Request*

**Comment by jareware** [comment]
Sorry for not getting to this sooner.

> have some type of script (or ansible.com type playlist) that creates the environment. This could then be used to create a full SDcard image or Docker type container

I'm happy to report this is already the case: the image setup is [scripted to a very large degree](https://github.com/futurice/chilipie-kiosk/blob/master/docs/image-setup.sh). The script currently only supports macOS, but at the same time as adding support for the Pi 4 (see #61) it's being converted to also run on Linux.
