### ISSUE TITLE
Is there a way to launch an app in background at startup?

### ISSUE THREAD

**Issue by MrMoins** [futurice/chilipie-kiosk#65]
I would like to have NFC TOOLS KBC launching at startup, to emulate keyboard with a nfc card reader, is it possible and how can I do ? thx
https://www.wakdev.com/apps/nfc-tools-kbc.html

**Comment by jareware** [comment]
Generally any method of "raspbian run at startup" search results will probably work, but for the truly quick-and-dirty, you can always just stick your script into `~/.xsession` :)
