### ISSUE TITLE
Replace chrome with WEP?

### ISSUE THREAD

**Issue by matristain** [futurice/chilipie-kiosk#68]
Not really an issue , but a question.
Do you know about WEP (WebKit port for embedded and low-consumption computer devices)
WEP is supposed to work with hardware acceleration and WEBGL like this (https://alteredqualia.com/three/examples/webgl_pasta.html)

I've tried to make an WEP image for my raspberry but no luck building the embedded using  Buildroot or Yocto, I don't know how to use them, haven't heard of them before 😄.

I´m not sure about the benefits on performance or stability but sound like a good way to go for a kiosk project.

here are some examples about WPE projects:
https://medium.com/@decrocksam/building-wpe-webkit-for-raspberry-pi-3-cdbd7b5cb362
https://www.youtube.com/watch?v=Uh1j5y05ltI&t=3s
https://www.j1nx.nl/ict-matters/compiling-wpe-webkit-for-the-raspberrypi/

**Comment by jareware** [comment]
Thanks for the links, that's definitely an interesting project!

That said, I think the value proposition of chilipie-kiosk is that most sites are best tested on Chrome these days, so for the best user experience, we should keep that the default.
