### ISSUE TITLE
Faster flashing instructions

### ISSUE THREAD

**Issue by jareware** [futurice/chilipie-kiosk#7]
http://superuser.com/questions/631592/why-is-dev-rdisk-about-20-times-faster-than-dev-disk-in-mac-os-x

**Comment by Ozzee** [comment]
You can also use `ctrl + t` to get the status of the dd command while it is running.

**Comment by jareware** [comment]
This has been addressed in e6bac1a9be078706c7e8a545349d90fde2617641, which will be included in the `v1.2` image, which is going into pre-release testing next week.

Thanks for contributing! ❤️

**Comment by jareware** [comment]
Released in `v1.2`
