### ISSUE TITLE
Embedded twitter video autoplay?

### ISSUE THREAD

**Issue by OZ1SEJ** [futurice/chilipie-kiosk#70]
I'm using chilipie-kiosk for displaying an embedded twitter timeline. Videos in tweets apparently don't autoplay, and it seems like it's not possible, since the player actually isn't loaded until the user clicks the play icon. Do you know anything about how to solve this problem?

**Comment by jareware** [comment]
Nothing off the top of my head, I'm afraid!

Your best bet is probably to [run some user-script or extension](https://github.com/futurice/chilipie-kiosk/blob/master/docs/first-boot.md#customizing-chromium) that does this for you.

**Comment by OZ1SEJ** [comment]
Thank you! :-)
