### ISSUE TITLE
How to change start URL via SSH?

### ISSUE THREAD

**Issue by OZ1SEJ** [futurice/chilipie-kiosk#71]
Via keyboard, I've pointed chromium to my desired web page, and now it's running just fine. But I know that at some point, I will need to point chromium to a different address. Can't I do this via SSH, or will I need to plug in a keyboard to do that?

**Comment by jareware** [comment]
Please check out #38, and chime in to the discussion if you have additional ideas!

**Comment by OZ1SEJ** [comment]
I gather that this is not possible with chromium - I've installed VNC instead, so I can do it remotely. Thank you!

**Comment by matristain** [comment]
I´ve used something like this:

bash -c "export DISPLAY=:0; xdotool key F11 sleep 1 key ctrl+l sleep 1 type 'https://google.com'; xdotool sleep 1 key KP_Enter; xdotool key F11;"

Not very pro, bud useful.

**Comment by jareware** [comment]
@matristain that's exactly the kind of solution that many people are looking for!

I'll add it to the README if you don't mind. :smile:
