### ISSUE TITLE
Would this image work with raspberry 4?

### ISSUE THREAD

**Issue by minutuslausus** [futurice/chilipie-kiosk#77]
I think it would, but have no idea :)

**Comment by kpdillon** [comment]
It does not seem to. :-(

**Comment by darshana-danrox** [comment]
we will provide working image with in this week .

**Comment by kpdillon** [comment]
Thank you!  Looking very forward to it!

**Comment by jareware** [comment]
Hey, and thanks for your efforts @darshana-danrox!

Please report your findings in #61! Closing this one as duplicate.
