### ISSUE TITLE
chromium does not restart alfter ALT + F4

### ISSUE THREAD

**Issue by opasch** [futurice/chilipie-kiosk#83]
If I press ALT+F4 in order to close all tabs and windows the black screen with the logo and "please wait" appears and chromium does not restart. Only restarting the windows manager with CTRL+ALT+BACKSPACE.

**Comment by jareware** [comment]
This is a good point; I guess it can be useful being able to restart Chromium.

I'd love a PR which makes sure it restarts after exit!

**Comment by jareware** [comment]
In lieu of a PR, I'm going to go ahead and close this, with an instruction of: don't press Alt + F4. :joy:
