### ISSUE TITLE
how to lockdown chilipie?

### ISSUE THREAD

**Issue by topoppe** [futurice/chilipie-kiosk#86]
Hey folks, i´m just trying to lockdown my chilipie somehow: 
My problem is, that the rpi i´m running has a fullfeatured keyboard on it and i think that some people will try to get into the system instead just using the webpage i show them. 
So i have to disable the autologin on ctrl-alt-f2 and f3, and if possible also disable alt-f4 to make the system save. 
I know that there are some more shortcuts, but i hope they will not be tried ;) 

So, any idea or tip how i can achive this? 
Thanks,
Tobias

**Comment by jareware** [comment]
You should start by changing the password to something not default, removing the `pi` user from sudoers, and indeed remove the auto-logins. Then you'd want to look into disabling as many system-wide shortcuts as possible, and see which Chromium switches would make it harder to exit (look into `--kiosk` for example).

That said, you may have a hard time plugging every hole from a determined attacker. This is not the primary use case for chilipie-kiosk, but you're of course welcome to try hardening it for this use case.

Please report back! :)
