### ISSUE TITLE
Doesn't boot to GUI after installing VNC

### ISSUE THREAD

**Issue by OZ1SEJ** [futurice/chilipie-kiosk#87]
I downloaded the latest stable release (2.1.0), flashed to SD, put in Raspberry Pi 3 model B, booted, pressed ctrl-alt-F2, entered raspi-config, chose "Interfacing options" and VNC. When I enabled VNC server, I got a lot of errors, and VNC didn't work.

So I ran a `sudo apt update`, `sudo apt upgrade` and then enabled VNC in raspi-config. The output can be [seen here](https://pastebin.com/TkMZi3FC).

Now, when I boot, it starts up with a text login on top of the welcome image background.png. So the GUI doesn't boot.

If I go into raspi-config and choose "Boot Options" - "Desktop / CLI" - "Desktop Autologin", it tells me that I need to install lightdm, so that seems like the wrong way to go.

Help would be appreciated!

**Comment by jareware** [comment]
Hey there!

There's another issue (#38) with a lot of info regarding your use case. Please check it out.

With regard to updates, it's not really something we support (#11), and I wonder how that could be made more clear... :thinking:
