### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by lfuelling** [futurice/chilipie-kiosk#91]
Hi,

I want to customize the image before I flash it but unfortunately there are no build instructions available.
Or at least they are not easily locateable. 

Could you please add those instructions or point me to their location?

If you only have a build script and no docs, I'd like to create documentation for it.

Thanks for your help

Lukas

**Comment by jareware** [comment]
The image is created using https://github.com/futurice/chilipie-kiosk/blob/master/docs/image-setup.sh which is fairly well documented.

**Comment by lfuelling** [comment]
It is indeed, thanks :)
